### PR TITLE
EIWFY23Q4-1 Add safe rendering of HTML docs

### PR DESCRIPTION
**Pull request by slatlasdev**
Many of the Connect docs contain extensive HTML documentation.

We can safely render this with `rehype-raw` and `rehype-sanitize`.

Before:
image

After: 
image

### CODE REVIEW

**Review by robertmassaioli — APPROVED** [review]

**Comment by robertmassaioli** [comment]
Thanks for the great change. This looks good and I'll ship it shortly.

**Comment by slatlasdev** [comment]
Before you ship, I need to raise a PR to use the new "strict" versions of the schemas. As soon as the pipeline in the other repo finishes building and publishing them, I'll raise that PR here.

**Comment by robertmassaioli** [comment]
Is there a problem that will occur to ship with the less strict schemas?

**Comment by slatlasdev** [comment]
No, no problem, feel free to proceed while I get this issue with the generator fixed.

**Pull request merged**
